.MODEL SMALL 
.STACK 100H 
.DATA 
B DW 2 
A DW ? 
C DW ? 
.CODE 
MAIN PROC 
    MOV AX,@DATA 
    MOV DS,AX
     
    MOV AX,B ;MOV THE VALUE OF B IN AX 
    MUL B ;MULTIPLY VALUE ALuE OF Ax BY B(oR 2) lvIOV BkAX;
    MOV BX,AX 
    NEG AX  ;NEGATION THE VALUE OF 
    ADD AX,5 ;ADD 5 WITH AX MU 
    MOV A,AX ;MOV THE VALUE OF AX IN A L 
    MUL B ;MULTIPLY THE VALUE OF A BY B(OR 2) MOV 
    MUL BX ;MULTIPLY THE VALUE OF 2A BY 2B 
    MOV C,AX ;MOV AX VALUE IN C 
    
MOV A,4CH 
INT 21H 
END MAIN 